const packageData = [
  {
    id: "8",
    problem: "8-problem",
    oneLiner: "8-one-liner",
    eightLiner: "8-two-liner",
    package: "8-package",
    description: "8-description",
    whatGet: "8-what-you-get",
    price: 99.0,
  },
  {
    id: "7",
    problem: "7-problem",
    oneLiner: "7-one-liner",
    eightLiner: "7-two-liner",
    package: "7-package",
    description: "7-description",
    whatGet: "7-what-you-get",
    price: 119.0,
  },
  {
    id: "1",
    problem: "1-problem",
    oneLiner: "1-one-liner",
    package: "1-package",
    description: "1-description",
    whatGet: "1-what-you-get",
    price: 350.0,
  },
  {
    id: "2",
    problem: "2-problem",
    oneLiner: "2-one-liner",
    package: "2-package",
    description: "2-description",
    whatGet: "2-what-you-get",
    price: 644.0,
  },
  {
    id: "3",
    problem: "3-problem",
    oneLiner: "3-one-liner",
    package: "3-package",
    description: "3-description",
    whatGet: "3-what-you-get",
    price: 149.75,
  },
  {
    id: "4",
    problem: "4-problem",
    oneLiner: "4-one-liner",
    package: "4-package",
    description: "4-description",
    whatGet: "4-what-you-get",
    price: 230.51,
  },
  {
    id: "5",
    problem: "5-problem",
    oneLiner: "5-one-liner",
    package: "5-package",
    description: "5-description",
    whatGet: "5-what-you-get",
    price: 76.92,
  },
  {
    id: "6",
    problem: "6-problem",
    oneLiner: "6-one-liner",
    package: "6-package",
    description: "6-description",
    whatGet: "6-what-you-get",
    price: 102.0,
  },
];

export default packageData;
